### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by farhansj** [sifulan-access-federation/ifirexman-shibboleth-idp#4]
2022-09-20 22:04:42,832 - 10.42.2.0 - INFO [net.shibboleth.idp.authn.impl.JAASCredentialValidator:268] - Credential Validator jaas: Login by 'farhan' via 'ShibUserPassAuth' failed
javax.security.auth.login.LoginException: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: "{i"
	at java.base/java.net.URLDecoder.decode(URLDecoder.java:232)
	at java.base/java.net.URLDecoder.decode(URLDecoder.java:142)
	at com.mysql.cj.conf.ConnectionUrlParser.decode(ConnectionUrlParser.java:569)
	at com.mysql.cj.conf.ConnectionUrlParser.parseConnectionString(ConnectionUrlParser.java:167)
	at com.mysql.cj.conf.ConnectionUrlParser.<init>(ConnectionUrlParser.java:137)
	at com.mysql.cj.conf.ConnectionUrlParser.parseConnectionString(ConnectionUrlParser.java:119)
	at com.mysql.cj.conf.ConnectionUrl.getConnectionUrlInstance(ConnectionUrl.java:279)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:195)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at relationalLogin.DBLogin.validateUser(Unknown Source)
	at relationalLogin.SimpleLogin.login(Unknown Source)
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:747)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:672)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:670)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:670)
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:581)

**Comment by farhansj** [comment]
Fixed
